import 'boxicons';
import './css/main.css';
import './css/global.css';
import './themes/defaultTheme.ts';
import './components/buttons/AppButton.ts';
import './components/ExampleComponent.ts';
import './components/LightToggle.ts';
import './components/navigation';
import './components/cart';
